ITEM.name = "Kit du serrurier avancé"
ITEM.description = "Un kit de serrurier avancé"
ITEM.longdesc = "Grand kit d'outils divers destinés à tester les fonctions de sécurité avancées des serrures industrielles."
ITEM.model = "models/kek1ch/box_toolkit_2.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 30000
ITEM.busflag = "dev"
ITEM.securitytype =  "mechanical"
ITEM.securityquality = 5
ITEM.weight = 0.25