ITEM.name = "PDA Brute-Force"
ITEM.description = "Un PDA de force brute"
ITEM.longdesc = "Une paire de PDA modernes et performants avec divers exploits et logiciels à bord. Si tout échoue, ils essaient automatiquement de "deviner" le mot de passe du système, en utilisant la puissance combinée du GPU et du CPU pour y parvenir."
ITEM.model = "models/kek1ch/dev_pda.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 30000
ITEM.busflag = "dev"
ITEM.securitytype =  "computers"
ITEM.securityquality = 5
ITEM.weight = 0.25