ITEM.name = "Pulseur brut"
ITEM.description = "Un pulseur brut"
ITEM.longdesc = "Une batterie et un jeu de fils pour court-circuiter ou envoyer des impulsions dans les fils, parfois efficace pour contourner une sécurité électronique bon marché."
ITEM.model = "models/alyx_emptool_prop.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 1000
ITEM.busflag = "dev"
ITEM.securitytype =  "electronic"
ITEM.securityquality = 1
ITEM.weight = 0.25