ITEM.name = "Décoderr"
ITEM.description = "Un décodeur"
ITEM.longdesc = "Dispositif rare conçu pour craquer les systèmes de sécurité en décodant leurs clés."
ITEM.model = "models/alyx_emptool_prop.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 50000
ITEM.busflag = "dev"
ITEM.securitytype =  "electronic"
ITEM.securityquality = 6
ITEM.weight = 0.25