ITEM.name = "Clé pirate"
ITEM.description = "Une clé pirate"
ITEM.longdesc = "Clé USB contenant un logiciel conçu pour attaquer automatiquement les faiblesses des systèmes courants qui n'ont pas été mis à jour depuis un moment."
ITEM.model = "models/kek1ch/dev_flash_1.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 2000
ITEM.busflag = "dev"
ITEM.securitytype =  "computers"
ITEM.securityquality = 2
ITEM.weight = 0.25