ITEM.name = "Épingles à cheveux"
ITEM.description = "Un paquet d'épingles à cheveux"
ITEM.longdesc = "Outil de crochetage improvisé qui peut défaire des serrures bon marché. Les matériaux sont communs, mais qui porte des épingles à cheveux dans la zone ?"
ITEM.model = "models/kek1ch/box_toolkit_2.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 1000
ITEM.busflag = "dev"
ITEM.securitytype =  "mechanical"
ITEM.securityquality = 1
ITEM.weight = 0.05