ITEM.name = "Live USB"
ITEM.description = "Une Live USB"
ITEM.longdesc = "Une simple clé USB avec un logiciel pour diagnostiquer et réparer les problèmes d'ordinateur. Ou contourner une sécurité de mauvaise qualité."
ITEM.model = "models/kek1ch/dev_flash_1.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 1000
ITEM.busflag = "dev"
ITEM.securitytype =  "computers"
ITEM.securityquality = 1
ITEM.weight = 0.25