ITEM.name = "Mini kit de l'électricien"
ITEM.description = "Un mini kit d'électricien"
ITEM.longdesc = "Un petit ensemble d'outils permettant d'installer, de réparer et de contourner des dispositifs électroniques et de sécurité."
ITEM.model = "models/kek1ch/toolkit_p.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 4000
ITEM.busflag = "dev"
ITEM.securitytype =  "electronic"
ITEM.securityquality = 3
ITEM.weight = 0.25