ITEM.name = "Kit d'entretien électronique"
ITEM.description = "Un kit d'entretien électronique"
ITEM.longdesc = "Grand kit d'outils divers destinés à tester et à déverrouiller les coffres-forts des banques ou autres serrures mécaniques de pointe. Ainsi que néttoyer de l'électronique de basse gamme."
ITEM.model = "models/kek1ch/box_toolkit_2.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 50000
ITEM.busflag = "dev"
ITEM.securitytype =  "mechanical"
ITEM.securityquality = 6
ITEM.weight = 0.25