ITEM.name = "Manteau amélioré Bandit"
ITEM.model ="models/lostsignalproject/items/upgrades/upgro2.mdl"
ITEM.newModel ="models/stalker_greh/stalker_greh_0i.mdl"
ITEM.description= "Ancien Manteau amélioré Bandit"
ITEM.longdesc = "Un manteau conçu par la faction des Bandits, c'est un manteau de cuir amélioré, il est bien plus résistant. Et possède une cagoule avec un crane."
ITEM.width = 2
ITEM.height = 2
ITEM.price = 20000
ITEM.busflag = "dev"
ITEM.br = 0
ITEM.fbr = 0 
ITEM.ar = 0
ITEM.far = 0
ITEM.isHelmet = true
ITEM.isGasmask = false
ITEM.radProt = 0.9
ITEM.repairCost = ITEM.price/100*1
ITEM.ballisticlevels = {"l","ll","lll","ll","l"}
ITEM.img = ix.util.GetMaterial("cotz/ui/icons/outfit_jacket_duty2.png")
ITEM.noBusiness = true

ITEM.weight = 0.700
ITEM.miscslots = 2