ITEM.name = "DUTY tenue de combat"
ITEM.model ="models/lostsignalproject/items/upgrades/upgro2.mdl"
ITEM.newModel ="models/stalkertnb/psz9d_duty.mdl"
ITEM.description= "Tenue de combat avancée duty."
ITEM.longdesc = "Tenue de combat avancée utilisée par la faction DUTY."
ITEM.width = 2
ITEM.height = 2
ITEM.price = 100000
ITEM.busflag = "dev"
ITEM.br = 2
ITEM.fbr = 6
ITEM.ar = 0.40
ITEM.far = 2
ITEM.isHelmet = true
ITEM.isGasmask = true
ITEM.radProt = 0.9
ITEM.repairCost = ITEM.price/100*1
ITEM.ballisticlevels = {"l","ll","ll","ll","ll"}
ITEM.img = ix.util.GetMaterial("cotz/ui/icons/outfit_48.png")
ITEM.overlayPath = "vgui/overlays/hud_gas.png"
ITEM.noBusiness = true

ITEM.weight = 9.400
ITEM.miscslots = 4