ITEM.name = "FunnyWeed Exo"
ITEM.model ="models/kek1ch/exo_outfit.mdl"
ITEM.newModel ="models/stalkertnb/exo_funnyweed.mdl"
ITEM.description= "Armure Exo FunnyWeed"
ITEM.longdesc = "Cette armure est pas mal commercialisée dans la zone fantôme, elle est pratique pas trop lourde et bien résistante, en plus de posséder une armature d'exosquelette !"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 60000
ITEM.busflag = "dev"
ITEM.br = 0.15
ITEM.fbr = 16
ITEM.ar = 0.40
ITEM.far = 3
ITEM.isHelmet = true
ITEM.isGasmask = false
ITEM.radProt = 0.9
ITEM.repairCost = ITEM.price/100*1
ITEM.ballisticlevels = {"ll","lV","lV","lV","lll-a"}
ITEM.img = ix.util.GetMaterial("cotz/ui/icons/outfit_126.png")
ITEM.noBusiness = true

ITEM.weight = 10.400
ITEM.miscslots = 4